# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window_gui.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(665, 393)
        MainWindow.setMinimumSize(QtCore.QSize(665, 392))
        MainWindow.setMaximumSize(QtCore.QSize(665, 393))
        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/Settings.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_set_def_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_set_def_1.setMinimumSize(QtCore.QSize(265, 40))
        self.pushButton_set_def_1.setMaximumSize(QtCore.QSize(265, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.pushButton_set_def_1.setFont(font)
        self.pushButton_set_def_1.setObjectName("pushButton_set_def_1")
        self.gridLayout_2.addWidget(self.pushButton_set_def_1, 11, 0, 1, 2, QtCore.Qt.AlignHCenter)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem, 5, 0, 1, 4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setMinimumSize(QtCore.QSize(120, 40))
        self.label_5.setMaximumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5, 0, QtCore.Qt.AlignHCenter)
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setMinimumSize(QtCore.QSize(110, 38))
        self.comboBox_2.setMaximumSize(QtCore.QSize(110, 38))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setObjectName("comboBox_2")
        self.horizontalLayout_3.addWidget(self.comboBox_2, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_minus_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_minus_2.setMinimumSize(QtCore.QSize(20, 20))
        self.pushButton_minus_2.setMaximumSize(QtCore.QSize(20, 20))
        self.pushButton_minus_2.setStyleSheet("border: none")
        self.pushButton_minus_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/minus_black.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_minus_2.setIcon(icon1)
        self.pushButton_minus_2.setIconSize(QtCore.QSize(18, 18))
        self.pushButton_minus_2.setObjectName("pushButton_minus_2")
        self.verticalLayout_2.addWidget(self.pushButton_minus_2)
        self.pushButton_plus_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_plus_2.setMinimumSize(QtCore.QSize(20, 20))
        self.pushButton_plus_2.setMaximumSize(QtCore.QSize(20, 20))
        self.pushButton_plus_2.setStyleSheet("border: none")
        self.pushButton_plus_2.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/plus_black.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_plus_2.setIcon(icon2)
        self.pushButton_plus_2.setIconSize(QtCore.QSize(18, 18))
        self.pushButton_plus_2.setObjectName("pushButton_plus_2")
        self.verticalLayout_2.addWidget(self.pushButton_plus_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(32, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 8, 2, 3, 2)
        self.pushButton_ip_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ip_2.setMinimumSize(QtCore.QSize(265, 40))
        self.pushButton_ip_2.setMaximumSize(QtCore.QSize(265, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_ip_2.setFont(font)
        self.pushButton_ip_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/led_red.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_ip_2.setIcon(icon3)
        self.pushButton_ip_2.setObjectName("pushButton_ip_2")
        self.gridLayout_2.addWidget(self.pushButton_ip_2, 4, 2, 1, 2, QtCore.Qt.AlignHCenter)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem3 = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setMinimumSize(QtCore.QSize(120, 40))
        self.label_4.setMaximumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("")
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4, 0, QtCore.Qt.AlignHCenter)
        self.comboBox_1 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_1.setMinimumSize(QtCore.QSize(110, 38))
        self.comboBox_1.setMaximumSize(QtCore.QSize(110, 38))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.comboBox_1.setFont(font)
        self.comboBox_1.setObjectName("comboBox_1")
        self.horizontalLayout.addWidget(self.comboBox_1, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout.setContentsMargins(0, -1, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_minus_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_minus_1.setMinimumSize(QtCore.QSize(20, 20))
        self.pushButton_minus_1.setMaximumSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_minus_1.setFont(font)
        self.pushButton_minus_1.setStyleSheet("border: none;")
        self.pushButton_minus_1.setText("")
        self.pushButton_minus_1.setIcon(icon1)
        self.pushButton_minus_1.setIconSize(QtCore.QSize(18, 18))
        self.pushButton_minus_1.setObjectName("pushButton_minus_1")
        self.verticalLayout.addWidget(self.pushButton_minus_1)
        self.pushButton_plus_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_plus_1.setMinimumSize(QtCore.QSize(20, 20))
        self.pushButton_plus_1.setMaximumSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_plus_1.setFont(font)
        self.pushButton_plus_1.setStyleSheet("border: none;")
        self.pushButton_plus_1.setText("")
        self.pushButton_plus_1.setIcon(icon2)
        self.pushButton_plus_1.setIconSize(QtCore.QSize(18, 18))
        self.pushButton_plus_1.setObjectName("pushButton_plus_1")
        self.verticalLayout.addWidget(self.pushButton_plus_1)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem4 = QtWidgets.QSpacerItem(32, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.gridLayout_2.addLayout(self.horizontalLayout, 8, 0, 3, 2)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMinimumSize(QtCore.QSize(200, 0))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 2, 0, 1, 2)
        self.pushButton_set_def_2 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_set_def_2.sizePolicy().hasHeightForWidth())
        self.pushButton_set_def_2.setSizePolicy(sizePolicy)
        self.pushButton_set_def_2.setMinimumSize(QtCore.QSize(265, 40))
        self.pushButton_set_def_2.setMaximumSize(QtCore.QSize(265, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_set_def_2.setFont(font)
        self.pushButton_set_def_2.setObjectName("pushButton_set_def_2")
        self.gridLayout_2.addWidget(self.pushButton_set_def_2, 11, 2, 1, 2, QtCore.Qt.AlignHCenter)
        self.pushButton_def_2 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_def_2.sizePolicy().hasHeightForWidth())
        self.pushButton_def_2.setSizePolicy(sizePolicy)
        self.pushButton_def_2.setMinimumSize(QtCore.QSize(265, 40))
        self.pushButton_def_2.setMaximumSize(QtCore.QSize(265, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_def_2.setFont(font)
        self.pushButton_def_2.setObjectName("pushButton_def_2")
        self.gridLayout_2.addWidget(self.pushButton_def_2, 6, 2, 1, 2, QtCore.Qt.AlignHCenter)
        spacerItem5 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.gridLayout_2.addItem(spacerItem5, 12, 0, 1, 4)
        spacerItem6 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem6, 7, 0, 1, 4)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setMinimumSize(QtCore.QSize(200, 0))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 2, 1, 2)
        spacerItem7 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.gridLayout_2.addItem(spacerItem7, 1, 0, 1, 4)
        spacerItem8 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem8, 3, 0, 1, 4)
        self.pushButton_def_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_def_1.setMinimumSize(QtCore.QSize(265, 40))
        self.pushButton_def_1.setMaximumSize(QtCore.QSize(265, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_def_1.setFont(font)
        self.pushButton_def_1.setObjectName("pushButton_def_1")
        self.gridLayout_2.addWidget(self.pushButton_def_1, 6, 0, 1, 2, QtCore.Qt.AlignHCenter)
        self.pushButton_ip_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ip_1.setMinimumSize(QtCore.QSize(265, 40))
        self.pushButton_ip_1.setMaximumSize(QtCore.QSize(265, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_ip_1.setFont(font)
        self.pushButton_ip_1.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pushButton_ip_1.setAutoFillBackground(False)
        self.pushButton_ip_1.setIcon(icon3)
        self.pushButton_ip_1.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_ip_1.setCheckable(False)
        self.pushButton_ip_1.setAutoRepeat(False)
        self.pushButton_ip_1.setAutoExclusive(False)
        self.pushButton_ip_1.setObjectName("pushButton_ip_1")
        self.gridLayout_2.addWidget(self.pushButton_ip_1, 4, 0, 1, 2, QtCore.Qt.AlignHCenter)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(330, 0))
        self.label.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 4)
        self.gridLayout.addLayout(self.gridLayout_2, 1, 0, 1, 5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 665, 21))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menuBar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menuBar)
        self.action_settings = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/gear.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_settings.setIcon(icon4)
        self.action_settings.setMenuRole(QtWidgets.QAction.TextHeuristicRole)
        self.action_settings.setObjectName("action_settings")
        self.action_exit = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/exit.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_exit.setIcon(icon5)
        self.action_exit.setMenuRole(QtWidgets.QAction.TextHeuristicRole)
        self.action_exit.setIconVisibleInMenu(True)
        self.action_exit.setObjectName("action_exit")
        self.action_about = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/help.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_about.setIcon(icon6)
        self.action_about.setObjectName("action_about")
        self.action_instruction = QtWidgets.QAction(MainWindow)
        self.action_instruction.setObjectName("action_instruction")
        self.menu.addAction(self.action_settings)
        self.menu.addSeparator()
        self.menu.addAction(self.action_exit)
        self.menu_2.addAction(self.action_about)
        self.menu_2.addAction(self.action_instruction)
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.pushButton_ip_1, self.pushButton_def_1)
        MainWindow.setTabOrder(self.pushButton_def_1, self.comboBox_1)
        MainWindow.setTabOrder(self.comboBox_1, self.pushButton_minus_1)
        MainWindow.setTabOrder(self.pushButton_minus_1, self.pushButton_plus_1)
        MainWindow.setTabOrder(self.pushButton_plus_1, self.pushButton_set_def_1)
        MainWindow.setTabOrder(self.pushButton_set_def_1, self.pushButton_ip_2)
        MainWindow.setTabOrder(self.pushButton_ip_2, self.pushButton_def_2)
        MainWindow.setTabOrder(self.pushButton_def_2, self.comboBox_2)
        MainWindow.setTabOrder(self.comboBox_2, self.pushButton_minus_2)
        MainWindow.setTabOrder(self.pushButton_minus_2, self.pushButton_plus_2)
        MainWindow.setTabOrder(self.pushButton_plus_2, self.pushButton_set_def_2)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Управление аттенюаторами"))
        self.pushButton_set_def_1.setText(_translate("MainWindow", "Установить как значение\n"
"по умолчанию"))
        self.label_5.setText(_translate("MainWindow", "Ослабление:"))
        self.pushButton_ip_2.setText(_translate("MainWindow", "         IP: 192.168.10.85     "))
        self.label_4.setText(_translate("MainWindow", "Ослабление:"))
        self.label_2.setText(_translate("MainWindow", "1 комплект"))
        self.pushButton_set_def_2.setText(_translate("MainWindow", "Установить как значение\n"
"по умолчанию"))
        self.pushButton_def_2.setText(_translate("MainWindow", "По умолчанию: 4.5 дБ"))
        self.label_3.setText(_translate("MainWindow", "2 комплект"))
        self.pushButton_def_1.setText(_translate("MainWindow", "По умолчанию: 4.5 дБ"))
        self.pushButton_ip_1.setText(_translate("MainWindow", "         IP: 192.168.10.84     "))
        self.label.setText(_translate("MainWindow", "Управление аттенюаторами"))
        self.menu.setTitle(_translate("MainWindow", "Файл"))
        self.menu_2.setTitle(_translate("MainWindow", "Справка"))
        self.action_settings.setText(_translate("MainWindow", "Настройки"))
        self.action_exit.setText(_translate("MainWindow", "Выход"))
        self.action_about.setText(_translate("MainWindow", "О программе"))
        self.action_instruction.setText(_translate("MainWindow", "Инструкция"))
import resources_rc
