# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings_gui.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(318, 270)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(318, 270))
        Form.setMaximumSize(QtCore.QSize(318, 270))
        font = QtGui.QFont()
        font.setPointSize(10)
        Form.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/Settings.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_save = QtWidgets.QPushButton(Form)
        self.pushButton_save.setObjectName("pushButton_save")
        self.gridLayout_2.addWidget(self.pushButton_save, 6, 0, 1, 1)
        self.pushButton_cancel = QtWidgets.QPushButton(Form)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.gridLayout_2.addWidget(self.pushButton_cancel, 6, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit_ip_1 = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_ip_1.sizePolicy().hasHeightForWidth())
        self.lineEdit_ip_1.setSizePolicy(sizePolicy)
        self.lineEdit_ip_1.setMaximumSize(QtCore.QSize(120, 16777215))
        self.lineEdit_ip_1.setObjectName("lineEdit_ip_1")
        self.gridLayout_3.addWidget(self.lineEdit_ip_1, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEdit_tl_1 = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_tl_1.sizePolicy().hasHeightForWidth())
        self.lineEdit_tl_1.setSizePolicy(sizePolicy)
        self.lineEdit_tl_1.setMaximumSize(QtCore.QSize(120, 16777215))
        self.lineEdit_tl_1.setObjectName("lineEdit_tl_1")
        self.gridLayout_3.addWidget(self.lineEdit_tl_1, 1, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 2, 0, 1, 2)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 0, 0, 1, 1)
        self.lineEdit_ip_2 = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_ip_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_ip_2.setSizePolicy(sizePolicy)
        self.lineEdit_ip_2.setMaximumSize(QtCore.QSize(120, 16777215))
        self.lineEdit_ip_2.setObjectName("lineEdit_ip_2")
        self.gridLayout_4.addWidget(self.lineEdit_ip_2, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 1, 0, 1, 1)
        self.lineEdit_tl_2 = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_tl_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_tl_2.setSizePolicy(sizePolicy)
        self.lineEdit_tl_2.setMaximumSize(QtCore.QSize(120, 16777215))
        self.lineEdit_tl_2.setObjectName("lineEdit_tl_2")
        self.gridLayout_4.addWidget(self.lineEdit_tl_2, 1, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 3, 0, 1, 2)
        self.checkBox_logs = QtWidgets.QCheckBox(Form)
        self.checkBox_logs.setObjectName("checkBox_logs")
        self.gridLayout_2.addWidget(self.checkBox_logs, 5, 0, 1, 2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setMinimumSize(QtCore.QSize(85, 0))
        self.label_5.setMaximumSize(QtCore.QSize(85, 16777215))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.comboBox_style = QtWidgets.QComboBox(Form)
        self.comboBox_style.setMinimumSize(QtCore.QSize(120, 0))
        self.comboBox_style.setMaximumSize(QtCore.QSize(120, 16777215))
        self.comboBox_style.setObjectName("comboBox_style")
        self.horizontalLayout.addWidget(self.comboBox_style)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout_2.addLayout(self.horizontalLayout, 4, 0, 1, 2)

        self.retranslateUi(Form)
        self.pushButton_cancel.clicked.connect(Form.close)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Настройки"))
        self.pushButton_save.setText(_translate("Form", "Сохранить"))
        self.pushButton_cancel.setText(_translate("Form", "Отмена"))
        self.groupBox.setTitle(_translate("Form", "1 комплект"))
        self.label.setText(_translate("Form", "IP-адрес:"))
        self.lineEdit_ip_1.setText(_translate("Form", "192.168.10.84"))
        self.label_2.setText(_translate("Form", "Собственные потери, дБ:"))
        self.lineEdit_tl_1.setText(_translate("Form", "4.5"))
        self.groupBox_2.setTitle(_translate("Form", "2 комплект"))
        self.label_3.setText(_translate("Form", "IP-адрес:"))
        self.lineEdit_ip_2.setText(_translate("Form", "192.168.10.85"))
        self.label_4.setText(_translate("Form", "Собственные потери, дБ:"))
        self.lineEdit_tl_2.setText(_translate("Form", "4.5"))
        self.checkBox_logs.setText(_translate("Form", "Записывать log-файлы"))
        self.label_5.setText(_translate("Form", "Оформление:"))
import resources_rc
